version: "3"

services:
    db:
        image: arm64v8/mysql:oracle
        command: --default-authentication-plugin=mysql_native_password
        expose:
            - 3306
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            #- /Applications/www/symfony-docker/var:/var/www/symfony/var
            #- /Applications/www/symfony-docker/vendor:/var/www/symfony/vendor
            #- /Applications/www/symfony-docker/drivers:/var/www/symfony/drivers
        networks:
            - symfony_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            #- /Applications/www/symfony-docker/var:/var/www/symfony/var
            #- /Applications/www/symfony-docker/vendor:/var/www/symfony/vendor
            #- /Applications/www/symfony-docker/drivers:/var/www/symfony/drivers
        ports:
            - 80:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local

    #chromedriver:
    #    image: debian:latest
    #    command: /usr/bin/chromedriver --whitelisted-ips=''

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    symfony_app:
